const cantonese: Record<string, string> = {
  "Observation Basketball": "Observation 籃球",
  Home: "主頁",
  Games: "賽事",
  Standings: "排名",
  Teams: "球隊",
  Players: "球員",
  Highlights: "精華",
  Photos: "相片",
  Videos: "影片",
  Predictions: "預測",
  "Photo Analysis": "相片分析",
  Settings: "設定",
  English: "英文",
  "Open navigation": "開啟導覽選單",
  "Close navigation": "關閉導覽選單",
  Language: "語言",
  "Enter full screen": "進入全螢幕",
  "Exit full screen": "離開全螢幕",
  "Full screen": "全螢幕",
  "Dark mode": "深色模式",
  "Light mode": "淺色模式",
  "Switch to dark mode": "切換至深色模式",
  "Switch to light mode": "切換至淺色模式",
  "Follow Observation Basketball": "追蹤 Observation Basketball",
  "OBS Basketball League": "OBS 籃球聯賽",
  Basketball: "籃球",
  "lives here.": "就喺呢度。",
  "Basketball lives here.": "籃球，就喺呢度。",
  "Live scores, league fixtures, standings, player statistics and game intelligence — all in one place.": "即時比數、聯賽賽程、排名、球員數據同賽事分析，全部一站睇晒。",
  "View Games": "查看賽事",
  "Browse Teams": "瀏覽球隊",
  Schedule: "賽程",
  "Coming Up": "即將舉行",
  "All Games": "所有賽事",
  "League Leaders": "聯賽領先球員",
  "Points Leader": "得分王",
  "Rebounds Leader": "籃板王",
  "Assists Leader": "助攻王",
  "All Players": "所有球員",
  Table: "積分榜",
  "Standings Snapshot": "排名概覽",
  "Full Standings": "完整排名",
  Latest: "最新",
  "Recent Results": "近期賽果",
  "Latest Result": "最新賽果",
  "View Game →": "查看賽事 →",
  "All Results": "所有賽果",
  "Live Games": "進行中賽事",
  Scheduled: "已排期",
  Live: "進行中",
  Finished: "已完場",
  live: "進行中",
  scheduled: "已排期",
  completed: "已完成",
  "No match is currently live.": "目前未有進行中賽事。",
  "No games are currently scheduled.": "目前未有已排期賽事。",
  "No scheduled games right now.": "暫時未有已排期賽事。",
  "No finished games yet.": "暫時未有已完場賽事。",
  "The league homepage is ready, but there is no active season to display yet.": "聯賽主頁已準備好，但暫時未有球季可以顯示。",
  Competition: "賽事",
  "Browse scheduled fixtures, live games and finished results. Search by team, venue, season or date.": "瀏覽已排期、進行中同已完場賽事，並可按球隊、場地、球季或日期搜尋。",
  Filters: "篩選",
  "Hide Filters": "收起篩選",
  "Clear Filters": "清除篩選",
  "Reset Filters": "重設篩選",
  Search: "搜尋",
  "Search team, venue, season, date or time...": "搜尋球隊、場地、球季、日期或時間...",
  Season: "球季",
  "All Seasons": "所有球季",
  League: "聯賽",
  Coast: "賽區",
  "All Coasts": "所有賽區",
  Team: "球隊",
  "All Teams": "所有球隊",
  From: "由",
  To: "至",
  Category: "類別",
  "Scheduled Games": "已排期賽事",
  "Finished Games": "已完場賽事",
  "No scheduled games found": "搵唔到已排期賽事",
  "No live games found": "暫時未有進行中賽事",
  "No finished games found": "搵唔到已完場賽事",
  "Scheduled games will appear here automatically once they are created.": "已排期賽事建立後會自動喺呢度顯示。",
  "West Coast": "西岸",
  "East Coast": "東岸",
  West: "西岸",
  East: "東岸",
  "View league standings by coast and season.": "按賽區同球季查看聯賽排名。",
  "Team Leaders": "球隊領先球員",
  Roster: "球員名單",
  "Recent Games": "近期賽事",
  "Upcoming Games": "即將舉行賽事",
  "Head-to-Head Record": "對賽紀錄",
  "Season Records": "球季紀錄",
  "W-L · DIFF": "勝-負 · 分差",
  "Shooting Splits": "投籃命中率",
  "Last 5 Games": "最近 5 場",
  "Season Games": "球季賽事",
  "Season by Season": "歷季表現",
  "Team Photos": "球隊相片",
  "Team Highlights": "球隊精華",
  "Search player...": "搜尋球員...",
  "Ask about live league data, photos, highlights, and AI photo analysis.": "查詢即時聯賽數據、相片、精華同 AI 相片分析。",
  "Try asking": "試下問",
  "+ New Chat": "+ 新對話",
  "New Chat": "新對話",
  "League data · photos · highlights · photo intelligence": "聯賽數據 · 相片 · 精華 · 相片智能分析",
  "Ask the league.": "問盡聯賽大小事。",
  "Ask Observation Basketball.": "向 Observation Basketball 發問。",
  "Explore league stats, player performance, recent form and matchup predictions through the OBS AI assistant.": "透過 OBS AI 助手探索聯賽數據、球員表現、近期狀態同對賽預測。",
  "Explore players, team form, standings, photos, highlights, AI photo/short-clip film analysis and data-driven matchup predictions.": "探索球員、球隊狀態、排名、相片、精華、AI 相片及短片分析，同數據主導嘅對賽預測。",
  "Who leads the league in scoring?": "邊位球員係聯賽得分王？",
  "Compare two teams this season": "比較今季兩支球隊",
  "Predict the next matchup": "預測下一場對賽",
  "Open OBS AI": "開啟 OBS AI",
  "Live scores, schedule and results.": "即時比數、賽程同賽果。",
  "West and East league tables.": "西岸同東岸聯賽排名。",
  "Rosters, records and team pages.": "球員名單、戰績同球隊專頁。",
  "Full player statistics and leaders.": "完整球員數據同領先榜。",
  "Show me photos from VISION's latest game": "俾我睇 VISION 最近一場賽事嘅相片",
  "Find videos from OBS Zero's most recent game": "搵 OBS Zero 最近一場賽事嘅影片",
  "Show me REBOUND KING photos and highlights": "俾我睇 REBOUND KING 嘅相片同精華",
  "What games are coming up?": "有咩賽事即將舉行？",
  "Predict VISION vs OBS Zero": "預測 VISION 對 OBS Zero",
  "Ask about stats, photos, highlights, a player, team, or game…": "查詢數據、相片、精華、球員、球隊或賽事…",
  "Send message": "傳送訊息",
  Send: "傳送",
  "Enter to send · Shift+Enter for new line": "按 Enter 傳送 · Shift+Enter 換行",
  "Uses OBS data + media": "使用 OBS 數據及媒體",
  "Checking OBS data & media…": "正在查閱 OBS 數據同媒體…",
  "OBS AI could not answer that request.": "OBS AI 未能回答呢個問題。",
  "OBS AI is temporarily unavailable.": "OBS AI 暫時未能使用。",
  "I couldn't generate an answer.": "我未能產生答案。",
  "Loading OBS photos...": "正在載入 OBS 相片...",
  "Open slideshow": "開啟幻燈片",
  "Choose an Album": "選擇相簿",
  "Close slideshow": "關閉幻燈片",
  "Previous photo": "上一張相片",
  "Next photo": "下一張相片",
  "Use ← → to navigate · Esc to close": "用 ← → 瀏覽 · 按 Esc 關閉",
  "Swipe-style navigation with the arrows": "用箭嘴切換相片",
  Administration: "管理",
  "Scorer Dashboard": "計分員控制台",
  "Live game control and league administration.": "即場賽事控制同聯賽管理。",
  Dashboard: "控制台",
  Seasons: "球季",
  season: "個球季",
  seasons: "個球季",
  league: "個聯賽",
  leagues: "個聯賽",
  players: "位球員",
  Fixtures: "賽程",
  "Ongoing Matches": "進行中賽事",
  "Scheduled Games": "已排期賽事",
  "Live Now": "現正進行",
  "Resume Scoring": "繼續計分",
  "All Games →": "所有賽事 →",
  "Game Operations": "賽事管理",
  "Manage Teams": "管理球隊",
  "Manage Seasons": "管理球季",
  "Manage Highlights": "管理精華",
  "Manage Photos": "管理相片",
  "Public Games": "公開賽事",
  "Resume a live game, edit upcoming fixtures or schedule the next match.": "繼續即場賽事、編輯即將舉行嘅賽程或安排下一場比賽。",
  "Create teams and assign managers for the selected season.": "為所選球季建立球隊同指派領隊。",
  "Set up the next season and copy existing teams and rosters.": "設定下一個球季，並複製現有球隊同球員名單。",
  "Quick-link YouTube videos to games and teams.": "快速將 YouTube 影片連結至賽事同球隊。",
  "Add a Google Drive folder once, then sync its photos to games and teams.": "加入 Google Drive 資料夾後，將相片同步至賽事同球隊。",
  "Open the public games and results page.": "開啟公開賽事及賽果頁面。",
  "Resume live matches, manage scheduled fixtures and create new games.": "繼續即場賽事、管理已排期賽事同建立新賽事。",
  "If you leave a live scorer, resume it here without starting a new match.": "離開即場計分器後，可以喺呢度繼續計分，毋須建立新賽事。",
  "Open a fixture when it is time to score. Admins can edit or delete it before it starts.": "賽事開始時開啟賽程進行計分；管理員可以喺開始前編輯或刪除賽事。",
  "Public Calendar": "公開賽程",
  "Season Management": "球季管理",
  "Create, edit and safely remove seasons.": "建立、編輯同安全刪除球季。",
  "Administrator access required": "需要管理員權限",
  "Season and team management are available to administrators only.": "只有管理員可以管理球季同球隊。",
  Admin: "管理",
  Leagues: "聯賽",
  "League Management": "聯賽管理",
  "Create and manage leagues, then create, edit and safely remove seasons inside them.": "建立同管理聯賽，再喺聯賽內建立、編輯及安全刪除球季。",
  "Add a new league or rename an existing one. A league can only be deleted after all of its seasons are removed.": "新增聯賽或重新命名現有聯賽。刪除聯賽前必須先移除所有球季。",
  "Add League": "新增聯賽",
  "No leagues have been created yet.": "暫時未有聯賽。",
  "League Name": "聯賽名稱",
  "Save Changes": "儲存變更",
  "Delete the league's seasons first": "請先刪除聯賽內嘅球季",
  "Existing Seasons": "現有球季",
  "No seasons have been created yet.": "暫時未有球季。",
  "Season Name": "球季名稱",
  "Season Year": "球季年份",
  "New Season": "新球季",
  "Create Season": "建立球季",
  "Select League": "選擇聯賽",
  "Copy teams and rosters from previous season": "複製上一季嘅球隊同球員名單",
  "Useful when most teams and players remain the same next season.": "適合下季大部分球隊同球員維持不變時使用。",
  "Copy From": "複製自",
  "Select Season": "選擇球季",
  "Add Season": "新增球季",
  "Create a new team or add an existing team to another season.": "建立新球隊，或將現有球隊加入另一個球季。",
  "Team Name": "球隊名稱",
  "You can type a brand-new team or select an existing team name.": "你可以輸入全新球隊，或者選擇現有球隊名稱。",
  Manager: "領隊",
  "Manager:": "領隊：",
  "· Home:": "· 主場：",
  "· Away:": "· 作客：",
  "Manager Email": "領隊電郵",
  "The manager should register using this exact email address.": "領隊需要使用呢個電郵地址註冊。",
  "Home Colour": "主場球衣顏色",
  "Away Colour": "作客球衣顏色",
  "Add Team": "新增球隊",
  "Existing Teams": "現有球隊",
  "Edit or Delete Team": "編輯或刪除球隊",
  "Edit the team name, coast, manager and kit colours. Delete removes the team from the selected season and is blocked if that team already has games in the season.": "編輯球隊名稱、賽區、領隊同球衣顏色。如果球隊今季已有賽事，系統會阻止刪除以保留紀錄。",
  "Team Logo": "球隊標誌",
  "JPG, PNG, WEBP or GIF. Maximum 5 MB.": "支援 JPG、PNG、WEBP 或 GIF，檔案上限 5 MB。",
  "Upload Logo": "上載標誌",
  "Replace Logo": "更換標誌",
  "Remove Logo": "移除標誌",
  "No teams are assigned to this season yet.": "呢個球季暫時未有球隊。",
  Rosters: "球員名單",
  "Add or Remove Players": "新增或移除球員",
  "Select a season and team, then manage that team's active roster. Removing a player does not delete the player or their historical records.": "選擇球季同球隊後管理現役名單。移除球員唔會刪除球員資料或歷史紀錄。",
  "Select Team": "選擇球隊",
  "Select a season to manage a roster.": "請選擇球季以管理球員名單。",
  "There are no teams in this season yet.": "呢個球季暫時未有球隊。",
  "Selected Team": "所選球隊",
  "Edit player names and jersey numbers. Name changes apply to the same player everywhere.": "編輯球員姓名同球衣號碼；姓名變更會套用至所有相關紀錄。",
  "Loading roster...": "正在載入球員名單...",
  "No players are currently on this roster.": "呢份名單暫時未有球員。",
  "Remove player photo": "移除球員相片",
  "Uploading photo...": "正在上載相片...",
  Remove: "移除",
  "Add Player": "新增球員",
  "+ Add Player": "+ 新增球員",
  "Add to Roster": "加入名單",
  "New Player": "新球員",
  "Existing Player": "現有球員",
  "Player Name": "球員姓名",
  "Select Player": "選擇球員",
  "Jersey Number": "球衣號碼",
  History: "紀錄",
  "Completed Games": "已完場賽事",
  "Admins can correct a completed game's date, time, venue, final score and Q1-Q5 scores, or permanently delete the game and all of its game-specific stats.": "管理員可以修正已完場賽事嘅日期、時間、場地、最終比數同 Q1 至 Q5 比數，亦可以永久刪除賽事及相關數據。",
  "Show All": "顯示全部",
  "Show Recent": "顯示近期",
  "Editing the final score does not redistribute points between players. Use this for correcting the official result or quarter scores. A future player box-score editor can handle individual player-stat corrections.": "修改最終比數唔會重新分配球員得分，只適用於修正官方賽果或各節比數。個別球員數據需使用球員統計編輯功能修正。",
  "No completed games yet.": "暫時未有已完場賽事。",
  Manual: "手動",
  "Venue not set": "未設定場地",
  "Edit Result": "編輯賽果",
  "Delete Game & Data": "刪除賽事及數據",
  "Editing Completed Result": "正在編輯已完場賽果",
  "Teams and season are locked for completed games so existing player/team statistics stay attached to the correct game.": "已完場賽事嘅球隊同球季會被鎖定，確保現有球員及球隊數據連結至正確賽事。",
  "Game Date": "賽事日期",
  "Game Time": "賽事時間",
  "Final Score": "最終比數",
  "Quarter Scores": "各節比數",
  "Q1 through Q5 are editable independently from the final score because some imported historical games do not have complete quarter breakdowns.": "Q1 至 Q5 可以同最終比數分開編輯，因為部分匯入嘅歷史賽事未有完整分節數據。",
  "Save Completed Game": "儲存已完場賽事",
  "Editing Fixture": "正在編輯賽程",
  "Select Home Team": "選擇主隊",
  "Select Away Team": "選擇客隊",
  "Quarter Lengths": "每節時間",
  minutes: "分鐘",
  "— West": "— 西岸",
  "— East": "— 東岸",
  "Fixture Scheduling": "賽程安排",
  "Schedule Game": "安排賽事",
  "Save the fixture now and open the scorer later when the game is ready to begin.": "而家先儲存賽程，賽事準備開始時再開啟計分器。",
  "This season does not have any teams yet. Add teams above before creating a game.": "呢個球季暫時未有球隊，請先新增球隊再建立賽事。",
  "Set the duration of Q1 through Q5.": "設定 Q1 至 Q5 嘅每節時間。",
  "Loading scorer dashboard...": "正在載入計分員控制台...",
  "Creating...": "正在建立...",
  "Creating Season...": "正在建立球季...",
  "Adding Team...": "正在新增球隊...",
  "Adding...": "正在新增...",
  "Saving...": "正在儲存...",
  "Uploading...": "正在上載...",
  "Deleting...": "正在刪除...",
  "Removing...": "正在移除...",
  "Scheduling Game...": "正在安排賽事...",
  "Team Management": "球隊管理",
  "Create teams, assign managers and manage season rosters.": "建立球隊、指派領隊同管理球季名單。",
  "Game date is required.": "必須填寫賽事日期。",
  "All scores must be whole numbers of 0 or more.": "所有比數必須係 0 或以上嘅整數。",
  "Administrator access required.": "需要管理員權限。",
  "You do not have scorer access.": "你未有計分員權限。",
  "Please enter a league name.": "請輸入聯賽名稱。",
  "League name is required.": "必須填寫聯賽名稱。",
  "Please select a league.": "請選擇聯賽。",
  "Please enter a season name.": "請輸入球季名稱。",
  "Please enter a valid season year.": "請輸入有效嘅球季年份。",
  "Season name is required.": "必須填寫球季名稱。",
  "Season year must be between 1900 and 2200.": "球季年份必須介乎 1900 至 2200。",
  "Please select a season to copy from.": "請選擇要複製嘅球季。",
  "Please enter a team name.": "請輸入球隊名稱。",
  "Team name is required.": "必須填寫球隊名稱。",
  "Please select West Coast or East Coast.": "請選擇西岸或東岸。",
  "Please select a season.": "請選擇球季。",
  "Please select a season and team first.": "請先選擇球季同球隊。",
  "Please enter the new player's name.": "請輸入新球員姓名。",
  "Please select an existing player.": "請選擇現有球員。",
  "Jersey number must be a whole number between 0 and 999.": "球衣號碼必須係 0 至 999 嘅整數。",
  "Player name cannot be blank.": "球員姓名唔可以留空。",
  "Please choose a JPG, PNG, WEBP or GIF image up to 5 MB.": "請選擇不超過 5 MB 嘅 JPG、PNG、WEBP 或 GIF 圖片。",
  "Season, home team, away team and game date are required.": "必須填寫球季、主隊、客隊同賽事日期。",
  "Home and away teams cannot be the same.": "主隊同客隊唔可以係同一支球隊。",
  "Quarter lengths must be between 1 and 60 minutes.": "每節時間必須介乎 1 至 60 分鐘。",
  "Please select both teams.": "請選擇兩支球隊。",
  "Quarter lengths must be at least 1 minute.": "每節時間最少要 1 分鐘。",
  "Your login session has expired. Please sign in again.": "登入時段已過期，請重新登入。",
  "Login failed.": "登入失敗。",
  "Your account does not currently have access to a team.": "你嘅帳戶暫時未獲授權存取球隊。",
  "Sign Out": "登出",
  Cancel: "取消",
  Edit: "編輯",
  Delete: "刪除",
  Save: "儲存",
  Update: "更新",
  Create: "建立",
  Add: "新增",
  Back: "返回",
  Optional: "選填",
  Venue: "場地",
  "League name": "聯賽名稱",
  "Enter team name": "輸入球隊名稱",
  "Manager name": "領隊姓名",
  "e.g. White": "例如：白色",
  "e.g. Red": "例如：紅色",
  "Upload player photo": "上載球員相片",
  "Basketball court / sports centre": "籃球場 / 體育中心",
  "No season": "不指定球季",
  "No specific game": "不指定賽事",
  "Current Links": "現有連結",
  "Linked Videos": "已連結影片",
  "No videos linked yet.": "暫時未有已連結影片。",
  "Public Page →": "公開頁面 →",
  "Loading highlights management…": "正在載入精華管理…",
  "YouTube Highlights": "YouTube 精華",
  "Loading photo management...": "正在載入相片管理...",
  "Syncing all Google Drive photo folders…": "正在同步所有 Google Drive 相片資料夾…",
  "Leave blank to use Home vs Away Photos": "留空會使用「主隊 對 客隊相片」",
  "Linked Photo Albums": "已連結相簿",
  "No games available for this season.": "呢個球季暫時未有賽事。",
  "No game log available yet.": "暫時未有賽事紀錄。",
  "Home Team": "主隊",
  "Away Team": "客隊",
  "Home": "主頁",
  "Away": "客隊",
  "Final": "完場",
};

const patterns: Array<[RegExp, (...matches: string[]) => string]> = [
  [/^(\d+) Scheduled$/, (_, count) => `${count} 場已排期`],
  [/^(\d+) Live$/, (_, count) => `${count} 場進行中`],
  [/^(\d+) Finished$/, (_, count) => `${count} 場已完場`],
  [/^(\d+) games$/, (_, count) => `${count} 場賽事`],
  [/^(\d+) games shown$/, (_, count) => `顯示 ${count} 場賽事`],
  [/^(\d+) leagues?$/, (_, count) => `${count} 個聯賽`],
  [/^(\d+) seasons?$/, (_, count) => `${count} 個球季`],
  [/^(\d+) players?$/, (_, count) => `${count} 位球員`],
  [/^(\d+) completed$/, (_, count) => `${count} 場已完場`],
  [/^Games · (\d+) LIVE$/, (_, count) => `賽事 · ${count} 場進行中`],
  [/^Game #(\d+)$/, (_, gameNumber) => `賽事 #${gameNumber}`],
  [/^Season (.+)$/, (_, season) => `球季 ${season}`],
  [/^Player ID: (.+)$/, (_, id) => `球員 ID：${id}`],
  [/^(.+) Final Score$/, (_, team) => `${team} 最終比數`],
  [/^Manager: (.+) · Home: (.+) · Away: (.+)$/, (_, manager, home, away) => `領隊：${manager} · 主場：${home} · 作客：${away}`],
  [/^(.+) — West$/, (_, team) => `${team} — 西岸`],
  [/^(.+) — East$/, (_, team) => `${team} — 東岸`],
  [/^Roster \((\d+)\)$/, (_, count) => `球員名單 (${count})`],
  [/^Round (\d+)$/, (_, round) => `第 ${round} 輪`],
  [/^Week (\d+)$/, (_, week) => `第 ${week} 週`],
  [/^Remove photo for (.+)$/, (_, name) => `移除 ${name} 嘅相片`],
  [/^Jersey number for (.+)$/, (_, name) => `${name} 嘅球衣號碼`],
  [/^Player name for (.+)$/, (_, name) => `${name} 嘅球員姓名`],
  [/^Jan (\d{1,2})$/, (_, day) => `1月${day}日`],
  [/^Feb (\d{1,2})$/, (_, day) => `2月${day}日`],
  [/^Mar (\d{1,2})$/, (_, day) => `3月${day}日`],
  [/^Apr (\d{1,2})$/, (_, day) => `4月${day}日`],
  [/^May (\d{1,2})$/, (_, day) => `5月${day}日`],
  [/^Jun (\d{1,2})$/, (_, day) => `6月${day}日`],
  [/^Jul (\d{1,2})$/, (_, day) => `7月${day}日`],
  [/^Aug (\d{1,2})$/, (_, day) => `8月${day}日`],
  [/^Sep (\d{1,2})$/, (_, day) => `9月${day}日`],
  [/^Oct (\d{1,2})$/, (_, day) => `10月${day}日`],
  [/^Nov (\d{1,2})$/, (_, day) => `11月${day}日`],
  [/^Dec (\d{1,2})$/, (_, day) => `12月${day}日`],
  [/^Jan (\d{1,2}), (\d{4})$/, (_, day, year) => `${year}年1月${day}日`],
  [/^Feb (\d{1,2}), (\d{4})$/, (_, day, year) => `${year}年2月${day}日`],
  [/^Mar (\d{1,2}), (\d{4})$/, (_, day, year) => `${year}年3月${day}日`],
  [/^Apr (\d{1,2}), (\d{4})$/, (_, day, year) => `${year}年4月${day}日`],
  [/^May (\d{1,2}), (\d{4})$/, (_, day, year) => `${year}年5月${day}日`],
  [/^Jun (\d{1,2}), (\d{4})$/, (_, day, year) => `${year}年6月${day}日`],
  [/^Jul (\d{1,2}), (\d{4})$/, (_, day, year) => `${year}年7月${day}日`],
  [/^Aug (\d{1,2}), (\d{4})$/, (_, day, year) => `${year}年8月${day}日`],
  [/^Sep (\d{1,2}), (\d{4})$/, (_, day, year) => `${year}年9月${day}日`],
  [/^Oct (\d{1,2}), (\d{4})$/, (_, day, year) => `${year}年10月${day}日`],
  [/^Nov (\d{1,2}), (\d{4})$/, (_, day, year) => `${year}年11月${day}日`],
  [/^Dec (\d{1,2}), (\d{4})$/, (_, day, year) => `${year}年12月${day}日`],
];

export function translateToCantonese(value: string) {
  const match = value.match(/^(\s*)(.*?)(\s*)$/s);

  if (!match || !match[2]) {
    return value;
  }

  const [, leading, content, trailing] = match;
  const exact = cantonese[content];

  if (exact) {
    return `${leading}${exact}${trailing}`;
  }

  for (const [pattern, replacement] of patterns) {
    const patternMatch = content.match(pattern);
    if (patternMatch) {
      return `${leading}${replacement(...patternMatch)}${trailing}`;
    }
  }

  return value;
}